### ISSUE TITLE
Undefined index: merchant

### ISSUE THREAD

**Issue by kunallibra** [sudiptpa/omnipay-nabtransact#25]
I am using **NABTransact_UnionPay** and I am using ->purchase() and then completePurchase()  but it is giving me an error as "Undefined index: merchant"

No sure how to fix this.

can someone help or advice me how to do it right please?

Thanks and much appreciated

**Comment by sudiptpa** [comment]
@kunallibra I will have a look at it for you.

**Comment by sudiptpa** [comment]
@kunallibra #26 now fixes issue with HMAC-SHA256 hashing support. The NAB Nov 2018 update requires this update.

Please update your composer.json file with new v3.0.1, and test with your integration.

**Comment by kunallibra** [comment]
hi, i updated   "league/omnipay": "3.0.1", version, but still the problem is same. having same errors.

thks

**Comment by kunallibra** [comment]
and it is pointing to this here in file (\vendor\sudiptpa\omnipay-nabtransact\src\Message\DirectPostCompletePurchaseRequest.php)

```
    public function generateResponseFingerprint($data)
    {
        $hash = implode('|', [
            $data['merchant'],
            $this->getTransactionPassword(),
            $data['refid'],
            $this->getAmount(),
            $data['timestamp'],
            $data['summarycode'],
        ]);
 
        return hash_hmac('sha256', $hash, true);
    }
```
