### ISSUE TITLE
Undefined index: merchant

### ISSUE THREAD

**Issue by kunallibra** [sudiptpa/omnipay-nabtransact#27]
after the nab 2018 update,  it is still pointing to the same error to the file (\vendor\sudiptpa\omnipay-nabtransact\src\Message\DirectPostCompletePurchaseRequest.php)

```
    public function generateResponseFingerprint($data)
    {
        $hash = implode('|', [
            $data['merchant'],
            $this->getTransactionPassword(),
            $data['refid'],
            $this->getAmount(),
            $data['timestamp'],
            $data['summarycode'],
        ]);
 
        return hash_hmac('sha256', $hash, true);
    }
```

**Comment by sudiptpa** [comment]
I guess, you are doing wrong integration, when the payment response comes from UnionPay Page that always comes with that merchant key.

Open issue with detailed error if you still have problem.
