### ISSUE TITLE
\Omnipay\NABTransact\SecureXMLGateway not found

### ISSUE THREAD

**Issue by niwang09** [sudiptpa/omnipay-nabtransact#28]
i tested it with newly installed vendor . but it gives me class \Omnipay\NABTransact\SecureXMLGateway not found . ive tried using this sample but no luck

          $gateway = Omnipay::create('NABTransact_SecureXML');

          $gateway->setMerchantId('6WZ0010'); //XYZ0010
          $gateway->setTransactionPassword('abc123'); //abcd1234

          $gateway->setTestMode(true);

**Comment by sudiptpa** [comment]
@niwang09 i just tested it works well no issue. Follow the example [here](https://github.com/sudiptpa/omnipay-nabtransact/blob/master/index.php)
