### ISSUE TITLE
Question - Invalid Fingerprint

### ISSUE THREAD

**Issue by bighoho123** [sudiptpa/omnipay-nabtransact#32]
Hi,

I am trying to use this libaray but using the basic example in readme

```
    $gateway = Omnipay::create('NABTransact_UnionPay');

    $gateway->setMerchantId('XYZ0010');
    $gateway->setTransactionPassword('abcd1234');

    $gateway->setTestMode(true);

    /*
     * The parameter transactionId must be alpha-numeric and 8 to 32 characters in length
     */

    $response = $gateway->purchase(array(
        'amount' => '12.00',
        'transactionId' => '1234566789205067',
        'currency' => 'AUD',
        'returnUrl' => 'http://example.com/payment/response',
    ))
        ->send();

    if ($response->isRedirect()) {
        $response->redirect();
    }
```

Will give me "invalid fingerprint" error message.

I contacted the NAB support and they seem to think the hmac signature should be the `$this->getTransactionPassword()` but in the library it is using `true`?

Is the example still working, or am i miss something?

**Comment by sudiptpa** [comment]
I have n't touched this library for a while, will give it a try soon to know if that still works and confirm if NAB has any changes in API side of things.

**Comment by bighoho123** [comment]
Hi @sudiptpa 

Thanks for that. Please let me know your finding after the test.

**Comment by bighoho123** [comment]
Hi @sudiptpa 
Did you have a chance to confirm your library is still working?
Thanks.

**Comment by sudiptpa** [comment]
@bighoho123 I've just tagged new release v3.0.2 with the fix for Invalid fingerprint, and updated tests as well.

I did some tests with sandbox account, and the Invalid fingerprint issue gone away, please check the latest version of package and let me know how you go.

Sorry for delay in responding, been a lot busy with work, so could not help on time.

**Comment by sudiptpa** [comment]
I was writting an article, but been busy, here is a complete code i've done and work in progress.

https://github.com/sudiptpa/blog-tutorials-v5.6/pull/7

**Comment by bighoho123** [comment]
Thanks for fixing that.

I can see the hmac secret has now been updated to the transactional password in your latest release which is what NAB told me. So it should be all good now.
