### ISSUE TITLE
How to use EMV 3D Secure Authentication

### ISSUE THREAD

**Issue by piyushgoyal789** [sudiptpa/omnipay-nabtransact#35]
Hi ,
Thanks for your work. I am wondering if your code support EMV 3D Secure Authentication . I am using your XML Risk management API . If you already added this let me know. 
Thanks.

**Comment by sudiptpa** [comment]
@piyushgoyal789 This [PR 36] (https://github.com/sudiptpa/omnipay-nabtransact/pull/36) adds support for EMV 3DSC

Feel free to test this and report, or submit a PR if you see any issue.

**Comment by piyushgoyal789** [comment]
Hi
Thank you very much.
Can you please tell how to use EMV 3DSC.
I mean we write as below

$gateway = Omnipay::create('NABTransact_SecureXML');
    $gateway->setMerchantId('XYZ0010');
    $gateway->setTransactionPassword('abcd1234');
    $gateway->setTestMode(true);
    $gateway->setRiskManagement(true);

so where we should write it? Can you suggest a method in read me.

Thanks again
Piyush
